//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantAbsolute.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeUser
    {
        public int id_TypeUser { get; set; }
        public string post { get; set; }
        public int id_post { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
